import { redactSecrets } from '../redact.js';

export type ApiErrorCode =
  | 'UNAUTHENTICATED'
  | 'FORBIDDEN'
  | 'SCOPE_DENIED'
  | 'ENGINE_NOT_ALLOWED'
  | 'ENGINE_REQUIRED'
  | 'MISSING_IDEMPOTENCY_KEY'
  | 'INVALID_REQUEST'
  | 'INVALID_REPOSITORY'
  | 'IDEMPOTENCY_CONFLICT'
  | 'TASK_ATTEMPT_ACTIVE'
  | 'NOT_FOUND'
  | 'ROUTE_NOT_FOUND'
  | 'METHOD_NOT_ALLOWED'
  | 'RESULT_NOT_READY'
  | 'STALE_OWNER_GENERATION'
  | 'CANCEL_REJECTED'
  | 'PAYLOAD_TOO_LARGE'
  | 'INTERNAL'
  | 'UPLOAD_SESSION_INVALID'
  | 'UPLOAD_SESSION_NOT_FOUND'
  | 'UPLOAD_SESSION_EXPIRED'
  | 'UPLOAD_HASH_MISMATCH'
  | 'UPLOAD_SIZE_MISMATCH'
  | 'CAPABILITY_NOT_FOUND'
  | 'CAPABILITY_BLOCKED'
  | 'CAPABILITY_MISSING_INPUT'
  | 'CAPABILITY_NEEDS_AGENT'
  | 'CAPABILITY_TECHNICAL_ERROR'
  | 'PROMOTION_PAUSED'
  | 'PAID_PROFILE_DISABLED'
  | 'COHORT_NOT_ENABLED'
  | 'TASK_OWNED_BY_OTHER_WORKER'
  | 'WORKER_DRAINING'
  | 'REGION_ENGINE_UNDECLARED'
  | 'REGION_ENGINE_FORBIDDEN'
  | 'REGION_EXPLICIT_PROFILE_REQUIRED'
  | 'REGION_NOT_ALLOWED'
  | 'PROVIDER_UNDECLARED'
  | 'PROVIDER_REGION_FORBIDDEN'
  | 'CREDENTIAL_SCOPE_UNDECLARED'
  | 'CREDENTIAL_REGION_FORBIDDEN'
  | 'DATA_RESIDENCY_UNDECIDED'
  | 'DATA_RESIDENCY_FORBIDDEN'
  | 'DATA_RESIDENCY_REGION_MISMATCH';

const HTTP_STATUS: Record<ApiErrorCode, number> = {
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  SCOPE_DENIED: 403,
  ENGINE_NOT_ALLOWED: 403,
  ENGINE_REQUIRED: 400,
  MISSING_IDEMPOTENCY_KEY: 400,
  INVALID_REQUEST: 400,
  INVALID_REPOSITORY: 400,
  IDEMPOTENCY_CONFLICT: 409,
  TASK_ATTEMPT_ACTIVE: 409,
  NOT_FOUND: 404,
  ROUTE_NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  RESULT_NOT_READY: 409,
  STALE_OWNER_GENERATION: 409,
  CANCEL_REJECTED: 409,
  PAYLOAD_TOO_LARGE: 413,
  INTERNAL: 500,
  UPLOAD_SESSION_INVALID: 400,
  UPLOAD_SESSION_NOT_FOUND: 404,
  UPLOAD_SESSION_EXPIRED: 410,
  UPLOAD_HASH_MISMATCH: 422,
  UPLOAD_SIZE_MISMATCH: 422,
  CAPABILITY_NOT_FOUND: 404,
  CAPABILITY_BLOCKED: 403,
  CAPABILITY_MISSING_INPUT: 400,
  CAPABILITY_NEEDS_AGENT: 409,
  CAPABILITY_TECHNICAL_ERROR: 502,
  PROMOTION_PAUSED: 503,
  PAID_PROFILE_DISABLED: 403,
  COHORT_NOT_ENABLED: 403,
  TASK_OWNED_BY_OTHER_WORKER: 409,
  WORKER_DRAINING: 503,
  REGION_ENGINE_UNDECLARED: 403,
  REGION_ENGINE_FORBIDDEN: 403,
  REGION_EXPLICIT_PROFILE_REQUIRED: 403,
  REGION_NOT_ALLOWED: 403,
  PROVIDER_UNDECLARED: 403,
  PROVIDER_REGION_FORBIDDEN: 403,
  CREDENTIAL_SCOPE_UNDECLARED: 403,
  CREDENTIAL_REGION_FORBIDDEN: 403,
  DATA_RESIDENCY_UNDECIDED: 409,
  DATA_RESIDENCY_FORBIDDEN: 403,
  DATA_RESIDENCY_REGION_MISMATCH: 403,
};

export interface ApiErrorBody {
  error: {
    code: ApiErrorCode;
    message: string;
    details?: Record<string, unknown>;
  };
}

export class ApiError extends Error {
  readonly code: ApiErrorCode;
  readonly status: number;
  readonly details?: Record<string, unknown>;

  constructor(code: ApiErrorCode, message: string, details?: Record<string, unknown>) {
    super(redactSecrets(message));
    this.name = 'ApiError';
    this.code = code;
    this.status = HTTP_STATUS[code];
    if (details !== undefined) this.details = details;
  }

  body(): ApiErrorBody {
    const error: ApiErrorBody['error'] = { code: this.code, message: this.message };
    if (this.details !== undefined) error.details = this.details;
    return { error };
  }
}
